# Generated by Django 5.1.4 on 2025-01-06 13:05

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='', max_length=100, unique=True)),
                ('blog_description', tinymce.models.HTMLField()),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('blog_author', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='', max_length=100, unique=True)),
                ('page_description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='postcategorymodel',
            name='cat_order',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
