# Generated by Django 5.1.4 on 2025-01-10 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogmodel_pagemodel_postcategorymodel_cat_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='post_Cat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='api.postcategorymodel'),
        ),
    ]
