# Generated by Django 5.1.4 on 2025-01-10 12:14

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blogmodel_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now, editable=False),
        ),
    ]
